apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.NAMESPACE }}
data:
  APP_ENV: "production"
  DB_HOST: "{{ .Values.APP_NAME }}-db"
  DB_PORT: "5432"
  UPLOAD_PATH: "/uploads"